- get_url: url='{{consul_url}}_darwin_amd64.zip' dest=/tmp/consul.zip validate_certs=no

- get_url: url='{{consul_ui_url}}' dest=/tmp/consul_ui.zip validate_certs=no

- name: create consul dir
  file: path={{item}} state=directory
  with_items:
    - '{{consul_dir}}'
    - '{{consul_dir}}/bin'
    - '{{consul_conf_dir}}'
    - '{{consul_data_dir}}'
    - '{{consul_log_dir}}'
    
- name: copy over distro agnostic unpack script
  template: src=unpack dest=/tmp/unpack mode=755

- name: unpack the consul archive
  command: /tmp/unpack /tmp/consul.zip {{consul_dir}}/bin

- name: unpack the consul_ui archive
  command: /tmp/unpack /tmp/consul_ui.zip {{consul_dir}}
  when: consul_server == true

- name: remove tmp consul zips
  file: path=/tmp/{{item}}.zip state=absent
  with_items:
    - consul_ui
    - consul
  
- name: make consul executable
  file: path="{{consul_dir}}/bin/consul" mode=755
