- name: supervisor started
  shell: ps -deaf | grep supervisord | grep -v grep | awk '{print $2};' | xargs kill -1
  notify: restart consul

- name: restart consul
  supervisorctl: name=consul state=restarted
